.TH "Objeto3d" 3 "Sat Mar 14 2015" "Version 1.0.0" "Body Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Objeto3d \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRotacionaX\fP (double teta)"
.br
.RI "\fIRotacionaX\&. \fP"
.ti -1c
.RI "void \fBRotacionaY\fP (double teta)"
.br
.RI "\fIRotacionaY\&. \fP"
.ti -1c
.RI "void \fBRotacionaZ\fP (double teta)"
.br
.RI "\fIRotacionaZ\&. \fP"
.ti -1c
.RI "void \fBDesenha\fP ()"
.br
.RI "\fIDesenha\&. \fP"
.ti -1c
.RI "GLdouble * \fBGetMatrizRotacao\fP ()"
.br
.RI "\fIGetMatrizRotacao\&. \fP"
.ti -1c
.RI "void \fBWriteData\fP (char *texto, GLfloat x, GLfloat y, GLfloat z)"
.br
.RI "\fIWriteData Desenha um texto na janela GLUT\&. \fP"
.ti -1c
.RI "void \fBAumentarEscala\fP ()"
.br
.RI "\fIAumentarEscala\&. \fP"
.ti -1c
.RI "void \fBDiminuirEscala\fP ()"
.br
.RI "\fIDiminuirEscala\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "GLdouble * Objeto3d::GetMatrizRotacao ()"

.PP
GetMatrizRotacao\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "void Objeto3d::RotacionaX (doubleteta)"

.PP
RotacionaX\&. 
.PP
\fBParameters:\fP
.RS 4
\fIteta\fP 
.RE
.PP

.SS "void Objeto3d::RotacionaY (doubleteta)"

.PP
RotacionaY\&. 
.PP
\fBParameters:\fP
.RS 4
\fIteta\fP 
.RE
.PP

.SS "void Objeto3d::RotacionaZ (doubleteta)"

.PP
RotacionaZ\&. 
.PP
\fBParameters:\fP
.RS 4
\fIteta\fP 
.RE
.PP

.SS "void Objeto3d::WriteData (char *texto, GLfloatx, GLfloaty, GLfloatz)"

.PP
WriteData Desenha um texto na janela GLUT\&. 
.PP
\fBParameters:\fP
.RS 4
\fItexto\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Body Tracker from the source code\&.
