.TH "Objeto3d" 3 "Tue Mar 17 2015" "Version 1.0.0" "Body Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Objeto3d \- 
.PP
Classe que representa um objeto 3D\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objeto3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjeto3d\fP ()"
.br
.RI "\fIConstrutor padrão\&. \fP"
.ti -1c
.RI "void \fBRotacionaX\fP (double theta)"
.br
.RI "\fIRotacionar o objeto no eixo X\&. \fP"
.ti -1c
.RI "void \fBRotacionaY\fP (double theta)"
.br
.RI "\fIRotacionar o objeto no eixo Y\&. \fP"
.ti -1c
.RI "void \fBRotacionaZ\fP (double theta)"
.br
.RI "\fIRotacionar o objeto no eixo Z\&. \fP"
.ti -1c
.RI "void \fBTranslada\fP (GLfloat *vetorTranslacao)"
.br
.RI "\fITransladar objeto nas coordenadas x,y e z\&. \fP"
.ti -1c
.RI "void \fBDesenha\fP ()"
.br
.RI "\fIDesenhar objeto\&. \fP"
.ti -1c
.RI "GLdouble * \fBGetMatrizRotacao\fP ()"
.br
.RI "\fIRecuperar matriz de rotação atual\&. \fP"
.ti -1c
.RI "void \fBWriteData\fP (char *texto, GLfloat x, GLfloat y, GLfloat z)"
.br
.RI "\fIEscrever informações do objeto em um ponto da janela\&. \fP"
.ti -1c
.RI "void \fBAumentarEscala\fP ()"
.br
.RI "\fIAumentar o fator de escala do objeto\&. \fP"
.ti -1c
.RI "void \fBDiminuirEscala\fP ()"
.br
.RI "\fIDiminuir o fator de escala do objeto\&. \fP"
.ti -1c
.RI "void \fBReiniciar\fP ()"
.br
.RI "\fIRetorna ao estado inicial do objeto\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Classe que representa um objeto 3D\&. 

Esta classe emgloba propriedades e operações disponíveis para um objeto 3D 
.SH "Member Function Documentation"
.PP 
.SS "GLdouble * Objeto3d::GetMatrizRotacao ()"

.PP
Recuperar matriz de rotação atual\&. 
.PP
\fBReturns:\fP
.RS 4
Vetor contendo os valores da matriz de rotação 
.RE
.PP

.SS "void Objeto3d::RotacionaX (doubletheta)"

.PP
Rotacionar o objeto no eixo X\&. Gerar a matrix de rotação no eixo X com o ângulo indicado 
.PP
\fBParameters:\fP
.RS 4
\fItheta\fP Angulo de rotação 
.RE
.PP

.SS "void Objeto3d::RotacionaY (doubletheta)"

.PP
Rotacionar o objeto no eixo Y\&. Gerar a matrix de rotação no eixo Y com o ângulo indicado 
.PP
\fBParameters:\fP
.RS 4
\fItheta\fP Angulo de rotação 
.RE
.PP

.SS "void Objeto3d::RotacionaZ (doubletheta)"

.PP
Rotacionar o objeto no eixo Z\&. Gerar a matrix de rotação no eixo Z com o ângulo indicado 
.PP
\fBParameters:\fP
.RS 4
\fItheta\fP Angulo de rotação 
.RE
.PP

.SS "void Objeto3d::Translada (GLfloat *vetorTranslacao)"

.PP
Transladar objeto nas coordenadas x,y e z\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvetorTranslacao\fP Vetor contendo os valores de translação 
.RE
.PP

.SS "void Objeto3d::WriteData (char *texto, GLfloatx, GLfloaty, GLfloatz)"

.PP
Escrever informações do objeto em um ponto da janela\&. 
.PP
\fBParameters:\fP
.RS 4
\fITexto\fP a ser escrito 
.br
\fIx\fP Posição X onde texto objeto será desenhado 
.br
\fIy\fP Posição Y onde texto objeto será desenhado 
.br
\fIz\fP Posição Z onde texto objeto será desenhado 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Body Tracker from the source code\&.
